{
 "title": "Pepper RIOT-FP debugging",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Nodes",
    "query": "show tag values with key = node_id"
   }
  ]
 },
 "panels": [
  {
   "title": "Resolved encounters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Nodes - Average ranging",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "repeat": "Nodes",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "contact_id" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "rpets",
       "select": [
        [
         { "params": [ "avg_d_cm" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "node_id", "operator": "=~", "value": "/^$Nodes$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Nodes Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node status",
     "type": "state-timeline",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "node_id" ], "type": "tag" },
        { "params": [ "node_id" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "status",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Node exposure",
     "type": "state-timeline",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "node_id" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "exposure",
       "select": [
        [
         { "params": [ "contact" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Node Infection",
     "type": "state-timeline",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "node_id" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "infection",
       "select": [
        [
         { "params": [ "infected" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    { "title": "Panel Title", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 } },
    {
     "title": "Panel Title",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "node_id" ], "type": "tag" }
       ],
       "measurement": "infection",
       "select": [
        [
         { "params": [ "infected" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}